# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(737, 585)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.topWidget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topWidget.sizePolicy().hasHeightForWidth())
        self.topWidget.setSizePolicy(sizePolicy)
        self.topWidget.setMinimumSize(QtCore.QSize(530, 54))
        self.topWidget.setMaximumSize(QtCore.QSize(16777215, 54))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(17, 98, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(17, 98, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(17, 98, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(17, 98, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(17, 98, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(17, 98, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(17, 98, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(17, 98, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(17, 98, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.topWidget.setPalette(palette)
        self.topWidget.setStyleSheet(_fromUtf8("background:rgb(17, 98, 160);"))
        self.topWidget.setObjectName(_fromUtf8("topWidget"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.topWidget)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.titleLbl = QtGui.QLabel(self.topWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(17, 98, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(17, 98, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(17, 98, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(17, 98, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(17, 98, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(17, 98, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(17, 98, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(17, 98, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(17, 98, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.titleLbl.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.titleLbl.setFont(font)
        self.titleLbl.setStyleSheet(_fromUtf8("color:rgb(255, 255, 255);"))
        self.titleLbl.setObjectName(_fromUtf8("titleLbl"))
        self.horizontalLayout_11.addWidget(self.titleLbl)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.settingsBtn = QtGui.QPushButton(self.topWidget)
        self.settingsBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settingsBtn.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/optionDark.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/optionDark.png")), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/option.png")), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/option.png")), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/optionDark.png")), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/option.png")), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/option.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/optionDark.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.settingsBtn.setIcon(icon)
        self.settingsBtn.setIconSize(QtCore.QSize(20, 20))
        self.settingsBtn.setAutoDefault(False)
        self.settingsBtn.setFlat(True)
        self.settingsBtn.setObjectName(_fromUtf8("settingsBtn"))
        self.horizontalLayout_4.addWidget(self.settingsBtn)
        self.newCourseBtn = QtGui.QPushButton(self.topWidget)
        self.newCourseBtn.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.newCourseBtn.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/newCourseDark.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newCourseBtn.setIcon(icon1)
        self.newCourseBtn.setIconSize(QtCore.QSize(20, 20))
        self.newCourseBtn.setAutoDefault(False)
        self.newCourseBtn.setFlat(True)
        self.newCourseBtn.setObjectName(_fromUtf8("newCourseBtn"))
        self.horizontalLayout_4.addWidget(self.newCourseBtn)
        self.newChapBtn = QtGui.QPushButton(self.topWidget)
        self.newChapBtn.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.newChapBtn.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/newChapDark.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newChapBtn.setIcon(icon2)
        self.newChapBtn.setIconSize(QtCore.QSize(20, 20))
        self.newChapBtn.setAutoDefault(False)
        self.newChapBtn.setFlat(True)
        self.newChapBtn.setObjectName(_fromUtf8("newChapBtn"))
        self.horizontalLayout_4.addWidget(self.newChapBtn)
        self.exitBtn = QtGui.QPushButton(self.topWidget)
        self.exitBtn.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.exitBtn.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/exitDark.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitBtn.setIcon(icon3)
        self.exitBtn.setIconSize(QtCore.QSize(20, 20))
        self.exitBtn.setAutoDefault(False)
        self.exitBtn.setFlat(True)
        self.exitBtn.setObjectName(_fromUtf8("exitBtn"))
        self.horizontalLayout_4.addWidget(self.exitBtn)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.minimizeBtn = QtGui.QPushButton(self.topWidget)
        self.minimizeBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeBtn.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/minimizeDark.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/minimizeDark.png")), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/minimize.png")), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/minimize.png")), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/minimizeDark.png")), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/minimize.png")), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/minimize.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/minimizeDark.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.minimizeBtn.setIcon(icon4)
        self.minimizeBtn.setIconSize(QtCore.QSize(24, 24))
        self.minimizeBtn.setFlat(True)
        self.minimizeBtn.setObjectName(_fromUtf8("minimizeBtn"))
        self.horizontalLayout.addWidget(self.minimizeBtn)
        self.closeBtn = QtGui.QPushButton(self.topWidget)
        self.closeBtn.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.closeBtn.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/closeDark.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/closeDark.png")), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/close.png")), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/closeDark.png")), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/close.png")), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/close.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/closeDark.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.closeBtn.setIcon(icon5)
        self.closeBtn.setIconSize(QtCore.QSize(24, 24))
        self.closeBtn.setFlat(True)
        self.closeBtn.setObjectName(_fromUtf8("closeBtn"))
        self.horizontalLayout.addWidget(self.closeBtn)
        self.horizontalLayout_11.addLayout(self.horizontalLayout)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)
        self.verticalLayout_3.addWidget(self.topWidget)
        self.mainWidget = QtGui.QStackedWidget(self.centralwidget)
        self.mainWidget.setFrameShadow(QtGui.QFrame.Raised)
        self.mainWidget.setObjectName(_fromUtf8("mainWidget"))
        self.mainPage = QtGui.QWidget()
        self.mainPage.setObjectName(_fromUtf8("mainPage"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.mainPage)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.leftWidget = QtGui.QWidget(self.mainPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftWidget.sizePolicy().hasHeightForWidth())
        self.leftWidget.setSizePolicy(sizePolicy)
        self.leftWidget.setMaximumSize(QtCore.QSize(192, 16777215))
        self.leftWidget.setObjectName(_fromUtf8("leftWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.leftWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.searchLE = QtGui.QLineEdit(self.leftWidget)
        self.searchLE.setMinimumSize(QtCore.QSize(191, 24))
        self.searchLE.setMaximumSize(QtCore.QSize(191, 24))
        self.searchLE.setAutoFillBackground(False)
        self.searchLE.setInputMask(_fromUtf8(""))
        self.searchLE.setText(_fromUtf8(""))
        self.searchLE.setObjectName(_fromUtf8("searchLE"))
        self.verticalLayout.addWidget(self.searchLE)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.userMenuBtn = QtGui.QPushButton(self.leftWidget)
        self.userMenuBtn.setMinimumSize(QtCore.QSize(0, 29))
        self.userMenuBtn.setMaximumSize(QtCore.QSize(16777215, 29))
        self.userMenuBtn.setObjectName(_fromUtf8("userMenuBtn"))
        self.horizontalLayout_2.addWidget(self.userMenuBtn)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.inboxBtn = QtGui.QPushButton(self.leftWidget)
        self.inboxBtn.setMinimumSize(QtCore.QSize(191, 28))
        self.inboxBtn.setMaximumSize(QtCore.QSize(191, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei UI"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.inboxBtn.setFont(font)
        self.inboxBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/table.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.inboxBtn.setIcon(icon6)
        self.inboxBtn.setIconSize(QtCore.QSize(24, 24))
        self.inboxBtn.setCheckable(True)
        self.inboxBtn.setChecked(False)
        self.inboxBtn.setFlat(True)
        self.inboxBtn.setObjectName(_fromUtf8("inboxBtn"))
        self.verticalLayout.addWidget(self.inboxBtn)
        self.starListBtn = QtGui.QPushButton(self.leftWidget)
        self.starListBtn.setMinimumSize(QtCore.QSize(191, 28))
        self.starListBtn.setMaximumSize(QtCore.QSize(191, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei UI"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.starListBtn.setFont(font)
        self.starListBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/tags.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.starListBtn.setIcon(icon7)
        self.starListBtn.setIconSize(QtCore.QSize(24, 24))
        self.starListBtn.setCheckable(True)
        self.starListBtn.setChecked(False)
        self.starListBtn.setFlat(True)
        self.starListBtn.setObjectName(_fromUtf8("starListBtn"))
        self.verticalLayout.addWidget(self.starListBtn)
        self.todayBtn = QtGui.QPushButton(self.leftWidget)
        self.todayBtn.setMinimumSize(QtCore.QSize(191, 28))
        self.todayBtn.setMaximumSize(QtCore.QSize(191, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei UI"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.todayBtn.setFont(font)
        self.todayBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/bookmark.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.todayBtn.setIcon(icon8)
        self.todayBtn.setIconSize(QtCore.QSize(24, 24))
        self.todayBtn.setCheckable(True)
        self.todayBtn.setChecked(False)
        self.todayBtn.setFlat(True)
        self.todayBtn.setObjectName(_fromUtf8("todayBtn"))
        self.verticalLayout.addWidget(self.todayBtn)
        self.weekBtn = QtGui.QPushButton(self.leftWidget)
        self.weekBtn.setMinimumSize(QtCore.QSize(191, 28))
        self.weekBtn.setMaximumSize(QtCore.QSize(191, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei UI"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.weekBtn.setFont(font)
        self.weekBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cube.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.weekBtn.setIcon(icon9)
        self.weekBtn.setIconSize(QtCore.QSize(24, 24))
        self.weekBtn.setCheckable(True)
        self.weekBtn.setChecked(False)
        self.weekBtn.setFlat(True)
        self.weekBtn.setObjectName(_fromUtf8("weekBtn"))
        self.verticalLayout.addWidget(self.weekBtn)
        self.listLW = QtGui.QListWidget(self.leftWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listLW.sizePolicy().hasHeightForWidth())
        self.listLW.setSizePolicy(sizePolicy)
        self.listLW.setMaximumSize(QtCore.QSize(191, 16777215))
        self.listLW.setObjectName(_fromUtf8("listLW"))
        self.verticalLayout.addWidget(self.listLW)
        self.addListBtn = QtGui.QPushButton(self.leftWidget)
        self.addListBtn.setMinimumSize(QtCore.QSize(191, 28))
        self.addListBtn.setMaximumSize(QtCore.QSize(191, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei UI"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.addListBtn.setFont(font)
        self.addListBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addListBtn.setIcon(icon9)
        self.addListBtn.setIconSize(QtCore.QSize(24, 24))
        self.addListBtn.setCheckable(True)
        self.addListBtn.setChecked(False)
        self.addListBtn.setFlat(True)
        self.addListBtn.setObjectName(_fromUtf8("addListBtn"))
        self.verticalLayout.addWidget(self.addListBtn)
        self.manageListBtn = QtGui.QPushButton(self.leftWidget)
        self.manageListBtn.setMinimumSize(QtCore.QSize(191, 28))
        self.manageListBtn.setMaximumSize(QtCore.QSize(191, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei UI"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.manageListBtn.setFont(font)
        self.manageListBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.manageListBtn.setIcon(icon9)
        self.manageListBtn.setIconSize(QtCore.QSize(24, 24))
        self.manageListBtn.setCheckable(True)
        self.manageListBtn.setChecked(False)
        self.manageListBtn.setFlat(True)
        self.manageListBtn.setObjectName(_fromUtf8("manageListBtn"))
        self.verticalLayout.addWidget(self.manageListBtn)
        spacerItem2 = QtGui.QSpacerItem(20, 92, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3.addWidget(self.leftWidget)
        self.mainStk = QtGui.QStackedWidget(self.mainPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainStk.sizePolicy().hasHeightForWidth())
        self.mainStk.setSizePolicy(sizePolicy)
        self.mainStk.setObjectName(_fromUtf8("mainStk"))
        self.homePage = QtGui.QWidget()
        self.homePage.setObjectName(_fromUtf8("homePage"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.homePage)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.addTaskBtn = QtGui.QPushButton(self.homePage)
        self.addTaskBtn.setMinimumSize(QtCore.QSize(41, 41))
        self.addTaskBtn.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.addTaskBtn.setFont(font)
        self.addTaskBtn.setIconSize(QtCore.QSize(24, 24))
        self.addTaskBtn.setFlat(True)
        self.addTaskBtn.setObjectName(_fromUtf8("addTaskBtn"))
        self.horizontalLayout_13.addWidget(self.addTaskBtn)
        self.addTaskLE = QtGui.QLineEdit(self.homePage)
        self.addTaskLE.setMinimumSize(QtCore.QSize(0, 41))
        self.addTaskLE.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.addTaskLE.setFont(font)
        self.addTaskLE.setObjectName(_fromUtf8("addTaskLE"))
        self.horizontalLayout_13.addWidget(self.addTaskLE)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.taskLW = QtGui.QListWidget(self.homePage)
        self.taskLW.setObjectName(_fromUtf8("taskLW"))
        self.verticalLayout_4.addWidget(self.taskLW)
        self.mainStk.addWidget(self.homePage)
        self.taskPage = QtGui.QWidget()
        self.taskPage.setObjectName(_fromUtf8("taskPage"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.taskPage)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.taskLbl = QtGui.QLabel(self.taskPage)
        self.taskLbl.setObjectName(_fromUtf8("taskLbl"))
        self.horizontalLayout_16.addWidget(self.taskLbl)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem3)
        self.onManualBtn = QtGui.QPushButton(self.taskPage)
        self.onManualBtn.setMinimumSize(QtCore.QSize(0, 29))
        self.onManualBtn.setObjectName(_fromUtf8("onManualBtn"))
        self.horizontalLayout_16.addWidget(self.onManualBtn)
        self.timerBtn = QtGui.QPushButton(self.taskPage)
        self.timerBtn.setMinimumSize(QtCore.QSize(0, 29))
        self.timerBtn.setObjectName(_fromUtf8("timerBtn"))
        self.horizontalLayout_16.addWidget(self.timerBtn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.addSubtaskBtn = QtGui.QPushButton(self.taskPage)
        self.addSubtaskBtn.setMinimumSize(QtCore.QSize(41, 41))
        self.addSubtaskBtn.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.addSubtaskBtn.setFont(font)
        self.addSubtaskBtn.setIconSize(QtCore.QSize(24, 24))
        self.addSubtaskBtn.setFlat(True)
        self.addSubtaskBtn.setObjectName(_fromUtf8("addSubtaskBtn"))
        self.horizontalLayout_14.addWidget(self.addSubtaskBtn)
        self.addSubtaskLE = QtGui.QLineEdit(self.taskPage)
        self.addSubtaskLE.setMinimumSize(QtCore.QSize(0, 41))
        self.addSubtaskLE.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.addSubtaskLE.setFont(font)
        self.addSubtaskLE.setObjectName(_fromUtf8("addSubtaskLE"))
        self.horizontalLayout_14.addWidget(self.addSubtaskLE)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.subtaskLW = QtGui.QListWidget(self.taskPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subtaskLW.sizePolicy().hasHeightForWidth())
        self.subtaskLW.setSizePolicy(sizePolicy)
        self.subtaskLW.setMinimumSize(QtCore.QSize(111, 29))
        self.subtaskLW.setMaximumSize(QtCore.QSize(11666, 16777215))
        self.subtaskLW.setObjectName(_fromUtf8("subtaskLW"))
        self.verticalLayout_5.addWidget(self.subtaskLW)
        spacerItem4 = QtGui.QSpacerItem(20, 206, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.mainStk.addWidget(self.taskPage)
        self.clockPage = QtGui.QWidget()
        self.clockPage.setObjectName(_fromUtf8("clockPage"))
        self.timerTitleLbl = QtGui.QLabel(self.clockPage)
        self.timerTitleLbl.setGeometry(QtCore.QRect(50, 40, 261, 21))
        self.timerTitleLbl.setMinimumSize(QtCore.QSize(0, 21))
        self.timerTitleLbl.setObjectName(_fromUtf8("timerTitleLbl"))
        self.groupBox = QtGui.QGroupBox(self.clockPage)
        self.groupBox.setGeometry(QtCore.QRect(90, 100, 311, 281))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.lcdLN = QtGui.QLCDNumber(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdLN.sizePolicy().hasHeightForWidth())
        self.lcdLN.setSizePolicy(sizePolicy)
        self.lcdLN.setNumDigits(8)
        self.lcdLN.setMode(QtGui.QLCDNumber.Bin)
        self.lcdLN.setObjectName(_fromUtf8("lcdLN"))
        self.verticalLayout_6.addWidget(self.lcdLN)
        self.startBtn = QtGui.QPushButton(self.groupBox)
        self.startBtn.setMinimumSize(QtCore.QSize(165, 41))
        self.startBtn.setObjectName(_fromUtf8("startBtn"))
        self.verticalLayout_6.addWidget(self.startBtn)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(3)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.resetBtn = QtGui.QPushButton(self.groupBox)
        self.resetBtn.setMinimumSize(QtCore.QSize(141, 41))
        self.resetBtn.setMaximumSize(QtCore.QSize(141, 41))
        self.resetBtn.setObjectName(_fromUtf8("resetBtn"))
        self.horizontalLayout_15.addWidget(self.resetBtn)
        self.stopBtn = QtGui.QPushButton(self.groupBox)
        self.stopBtn.setMinimumSize(QtCore.QSize(141, 41))
        self.stopBtn.setMaximumSize(QtCore.QSize(141, 41))
        self.stopBtn.setObjectName(_fromUtf8("stopBtn"))
        self.horizontalLayout_15.addWidget(self.stopBtn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.mainStk.addWidget(self.clockPage)
        self.recordPage = QtGui.QWidget()
        self.recordPage.setObjectName(_fromUtf8("recordPage"))
        self.recordTitleLbl = QtGui.QLabel(self.recordPage)
        self.recordTitleLbl.setGeometry(QtCore.QRect(50, 70, 221, 16))
        self.recordTitleLbl.setObjectName(_fromUtf8("recordTitleLbl"))
        self.label = QtGui.QLabel(self.recordPage)
        self.label.setGeometry(QtCore.QRect(60, 160, 54, 12))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_3 = QtGui.QLabel(self.recordPage)
        self.label_3.setGeometry(QtCore.QRect(60, 200, 54, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.todayDE = QtGui.QDateEdit(self.recordPage)
        self.todayDE.setGeometry(QtCore.QRect(110, 160, 110, 22))
        self.todayDE.setCalendarPopup(True)
        self.todayDE.setObjectName(_fromUtf8("todayDE"))
        self.minuteSpin = QtGui.QSpinBox(self.recordPage)
        self.minuteSpin.setGeometry(QtCore.QRect(230, 200, 61, 22))
        self.minuteSpin.setMaximum(59)
        self.minuteSpin.setObjectName(_fromUtf8("minuteSpin"))
        self.label_7 = QtGui.QLabel(self.recordPage)
        self.label_7.setGeometry(QtCore.QRect(310, 200, 54, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.recordPage)
        self.label_8.setGeometry(QtCore.QRect(60, 240, 54, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.minCountSpin = QtGui.QSpinBox(self.recordPage)
        self.minCountSpin.setGeometry(QtCore.QRect(120, 240, 51, 22))
        self.minCountSpin.setMaximum(9999)
        self.minCountSpin.setObjectName(_fromUtf8("minCountSpin"))
        self.slashLbl = QtGui.QLabel(self.recordPage)
        self.slashLbl.setGeometry(QtCore.QRect(180, 240, 21, 21))
        self.slashLbl.setObjectName(_fromUtf8("slashLbl"))
        self.maxCountSpin = QtGui.QSpinBox(self.recordPage)
        self.maxCountSpin.setGeometry(QtCore.QRect(210, 240, 51, 22))
        self.maxCountSpin.setMaximum(9999)
        self.maxCountSpin.setObjectName(_fromUtf8("maxCountSpin"))
        self.rangeCB = QtGui.QCheckBox(self.recordPage)
        self.rangeCB.setGeometry(QtCore.QRect(120, 280, 121, 16))
        self.rangeCB.setObjectName(_fromUtf8("rangeCB"))
        self.saveBtn = QtGui.QPushButton(self.recordPage)
        self.saveBtn.setGeometry(QtCore.QRect(300, 390, 75, 41))
        self.saveBtn.setMinimumSize(QtCore.QSize(0, 41))
        self.saveBtn.setMaximumSize(QtCore.QSize(16777215, 41))
        self.saveBtn.setObjectName(_fromUtf8("saveBtn"))
        self.label_9 = QtGui.QLabel(self.recordPage)
        self.label_9.setGeometry(QtCore.QRect(180, 200, 54, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.hourSpin = QtGui.QSpinBox(self.recordPage)
        self.hourSpin.setGeometry(QtCore.QRect(110, 200, 61, 22))
        self.hourSpin.setMaximum(59)
        self.hourSpin.setObjectName(_fromUtf8("hourSpin"))
        self.unitLbl = QtGui.QLabel(self.recordPage)
        self.unitLbl.setGeometry(QtCore.QRect(270, 250, 54, 12))
        self.unitLbl.setObjectName(_fromUtf8("unitLbl"))
        self.mainStk.addWidget(self.recordPage)
        self.listPage = QtGui.QWidget()
        self.listPage.setObjectName(_fromUtf8("listPage"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.listPage)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.addListTaskBtn = QtGui.QPushButton(self.listPage)
        self.addListTaskBtn.setMinimumSize(QtCore.QSize(41, 41))
        self.addListTaskBtn.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.addListTaskBtn.setFont(font)
        self.addListTaskBtn.setIconSize(QtCore.QSize(24, 24))
        self.addListTaskBtn.setFlat(True)
        self.addListTaskBtn.setObjectName(_fromUtf8("addListTaskBtn"))
        self.horizontalLayout_20.addWidget(self.addListTaskBtn)
        self.addListTaskLE = QtGui.QLineEdit(self.listPage)
        self.addListTaskLE.setMinimumSize(QtCore.QSize(0, 41))
        self.addListTaskLE.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.addListTaskLE.setFont(font)
        self.addListTaskLE.setObjectName(_fromUtf8("addListTaskLE"))
        self.horizontalLayout_20.addWidget(self.addListTaskLE)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.listTaskLW = QtGui.QListWidget(self.listPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listTaskLW.sizePolicy().hasHeightForWidth())
        self.listTaskLW.setSizePolicy(sizePolicy)
        self.listTaskLW.setMaximumSize(QtCore.QSize(16677, 16777215))
        self.listTaskLW.setObjectName(_fromUtf8("listTaskLW"))
        self.verticalLayout_7.addWidget(self.listTaskLW)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_11 = QtGui.QLabel(self.listPage)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_19.addWidget(self.label_11)
        self.unitCombo = QtGui.QComboBox(self.listPage)
        self.unitCombo.setEditable(True)
        self.unitCombo.setObjectName(_fromUtf8("unitCombo"))
        self.horizontalLayout_19.addWidget(self.unitCombo)
        self.unitBtn = QtGui.QPushButton(self.listPage)
        self.unitBtn.setMinimumSize(QtCore.QSize(0, 29))
        self.unitBtn.setObjectName(_fromUtf8("unitBtn"))
        self.horizontalLayout_19.addWidget(self.unitBtn)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem5)
        self.randomBtn = QtGui.QPushButton(self.listPage)
        self.randomBtn.setMinimumSize(QtCore.QSize(0, 29))
        self.randomBtn.setObjectName(_fromUtf8("randomBtn"))
        self.horizontalLayout_19.addWidget(self.randomBtn)
        self.importBtn = QtGui.QPushButton(self.listPage)
        self.importBtn.setMinimumSize(QtCore.QSize(0, 29))
        self.importBtn.setObjectName(_fromUtf8("importBtn"))
        self.horizontalLayout_19.addWidget(self.importBtn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.mainStk.addWidget(self.listPage)
        self.resultPage = QtGui.QWidget()
        self.resultPage.setObjectName(_fromUtf8("resultPage"))
        self.verticalLayoutWidget = QtGui.QWidget(self.resultPage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(39, 49, 211, 151))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.resultLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.resultLayout.setObjectName(_fromUtf8("resultLayout"))
        self.mainStk.addWidget(self.resultPage)
        self.horizontalLayout_3.addWidget(self.mainStk)
        self.mainWidget.addWidget(self.mainPage)
        self.configPage = QtGui.QWidget()
        self.configPage.setObjectName(_fromUtf8("configPage"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.configPage)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.configWidget = QtGui.QWidget(self.configPage)
        self.configWidget.setObjectName(_fromUtf8("configWidget"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.configWidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(50, 71, 411, 31))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(81, 0))
        self.label_5.setMaximumSize(QtCore.QSize(81, 16777215))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_8.addWidget(self.label_5)
        self.dbCombo = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbCombo.sizePolicy().hasHeightForWidth())
        self.dbCombo.setSizePolicy(sizePolicy)
        self.dbCombo.setEditable(True)
        self.dbCombo.setObjectName(_fromUtf8("dbCombo"))
        self.horizontalLayout_8.addWidget(self.dbCombo)
        self.dbPathBtn = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.dbPathBtn.setMinimumSize(QtCore.QSize(68, 0))
        self.dbPathBtn.setMaximumSize(QtCore.QSize(68, 16777215))
        self.dbPathBtn.setObjectName(_fromUtf8("dbPathBtn"))
        self.horizontalLayout_8.addWidget(self.dbPathBtn)
        self.settingsTitleLbl = QtGui.QLabel(self.configWidget)
        self.settingsTitleLbl.setGeometry(QtCore.QRect(40, 20, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.settingsTitleLbl.setFont(font)
        self.settingsTitleLbl.setObjectName(_fromUtf8("settingsTitleLbl"))
        self.horizontalLayoutWidget_18 = QtGui.QWidget(self.configWidget)
        self.horizontalLayoutWidget_18.setGeometry(QtCore.QRect(50, 220, 411, 31))
        self.horizontalLayoutWidget_18.setObjectName(_fromUtf8("horizontalLayoutWidget_18"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_18)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_17 = QtGui.QLabel(self.horizontalLayoutWidget_18)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(81, 0))
        self.label_17.setMaximumSize(QtCore.QSize(81, 16777215))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_18.addWidget(self.label_17)
        self.imageBankCombo = QtGui.QComboBox(self.horizontalLayoutWidget_18)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageBankCombo.sizePolicy().hasHeightForWidth())
        self.imageBankCombo.setSizePolicy(sizePolicy)
        self.imageBankCombo.setEditable(True)
        self.imageBankCombo.setObjectName(_fromUtf8("imageBankCombo"))
        self.horizontalLayout_18.addWidget(self.imageBankCombo)
        self.imageBankBtn = QtGui.QPushButton(self.horizontalLayoutWidget_18)
        self.imageBankBtn.setMinimumSize(QtCore.QSize(68, 0))
        self.imageBankBtn.setMaximumSize(QtCore.QSize(68, 16777215))
        self.imageBankBtn.setObjectName(_fromUtf8("imageBankBtn"))
        self.horizontalLayout_18.addWidget(self.imageBankBtn)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.configWidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(50, 101, 411, 31))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(81, 0))
        self.label_2.setMaximumSize(QtCore.QSize(81, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_6.addWidget(self.label_2)
        self.courseCombo = QtGui.QComboBox(self.horizontalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.courseCombo.sizePolicy().hasHeightForWidth())
        self.courseCombo.setSizePolicy(sizePolicy)
        self.courseCombo.setMinimumSize(QtCore.QSize(248, 0))
        self.courseCombo.setMaximumSize(QtCore.QSize(248, 16777215))
        self.courseCombo.setObjectName(_fromUtf8("courseCombo"))
        self.horizontalLayout_6.addWidget(self.courseCombo)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.horizontalLayoutWidget_17 = QtGui.QWidget(self.configWidget)
        self.horizontalLayoutWidget_17.setGeometry(QtCore.QRect(50, 250, 411, 31))
        self.horizontalLayoutWidget_17.setObjectName(_fromUtf8("horizontalLayoutWidget_17"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_17)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_26 = QtGui.QLabel(self.horizontalLayoutWidget_17)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(81, 0))
        self.label_26.setMaximumSize(QtCore.QSize(81, 16777215))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_17.addWidget(self.label_26)
        self.imgFormatCombo = QtGui.QComboBox(self.horizontalLayoutWidget_17)
        self.imgFormatCombo.setMinimumSize(QtCore.QSize(68, 0))
        self.imgFormatCombo.setMaximumSize(QtCore.QSize(68, 16777215))
        self.imgFormatCombo.setObjectName(_fromUtf8("imgFormatCombo"))
        self.imgFormatCombo.addItem(_fromUtf8(""))
        self.imgFormatCombo.addItem(_fromUtf8(""))
        self.imgFormatCombo.addItem(_fromUtf8(""))
        self.imgFormatCombo.addItem(_fromUtf8(""))
        self.horizontalLayout_17.addWidget(self.imgFormatCombo)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem7)
        self.horizontalLayoutWidget_10 = QtGui.QWidget(self.configWidget)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(50, 190, 411, 31))
        self.horizontalLayoutWidget_10.setObjectName(_fromUtf8("horizontalLayoutWidget_10"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_10 = QtGui.QLabel(self.horizontalLayoutWidget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(81, 0))
        self.label_10.setMaximumSize(QtCore.QSize(81, 16777215))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)
        self.audioBankCombo = QtGui.QComboBox(self.horizontalLayoutWidget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.audioBankCombo.sizePolicy().hasHeightForWidth())
        self.audioBankCombo.setSizePolicy(sizePolicy)
        self.audioBankCombo.setEditable(True)
        self.audioBankCombo.setObjectName(_fromUtf8("audioBankCombo"))
        self.horizontalLayout_9.addWidget(self.audioBankCombo)
        self.audioBankBtn = QtGui.QPushButton(self.horizontalLayoutWidget_10)
        self.audioBankBtn.setMinimumSize(QtCore.QSize(68, 0))
        self.audioBankBtn.setMaximumSize(QtCore.QSize(68, 16777215))
        self.audioBankBtn.setObjectName(_fromUtf8("audioBankBtn"))
        self.horizontalLayout_9.addWidget(self.audioBankBtn)
        self.saveSettingsBtn = QtGui.QPushButton(self.configWidget)
        self.saveSettingsBtn.setGeometry(QtCore.QRect(50, 301, 111, 29))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveSettingsBtn.sizePolicy().hasHeightForWidth())
        self.saveSettingsBtn.setSizePolicy(sizePolicy)
        self.saveSettingsBtn.setMinimumSize(QtCore.QSize(111, 29))
        self.saveSettingsBtn.setMaximumSize(QtCore.QSize(111, 29))
        self.saveSettingsBtn.setBaseSize(QtCore.QSize(111, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(12)
        self.saveSettingsBtn.setFont(font)
        self.saveSettingsBtn.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.saveSettingsBtn.setObjectName(_fromUtf8("saveSettingsBtn"))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.configWidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(50, 130, 411, 31))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(81, 0))
        self.label_4.setMaximumSize(QtCore.QSize(81, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.tempNumSpin = QtGui.QSpinBox(self.horizontalLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempNumSpin.sizePolicy().hasHeightForWidth())
        self.tempNumSpin.setSizePolicy(sizePolicy)
        self.tempNumSpin.setMaximumSize(QtCore.QSize(68, 16777215))
        self.tempNumSpin.setMinimum(1)
        self.tempNumSpin.setProperty("value", 15)
        self.tempNumSpin.setObjectName(_fromUtf8("tempNumSpin"))
        self.horizontalLayout_7.addWidget(self.tempNumSpin)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.gotoMainBtn = QtGui.QPushButton(self.configWidget)
        self.gotoMainBtn.setGeometry(QtCore.QRect(0, 0, 31, 31))
        self.gotoMainBtn.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.gotoMainBtn.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/backDark.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gotoMainBtn.setIcon(icon10)
        self.gotoMainBtn.setIconSize(QtCore.QSize(32, 32))
        self.gotoMainBtn.setAutoDefault(False)
        self.gotoMainBtn.setFlat(True)
        self.gotoMainBtn.setObjectName(_fromUtf8("gotoMainBtn"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.configWidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(49, 160, 411, 31))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(81, 0))
        self.label_6.setMaximumSize(QtCore.QSize(81, 16777215))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.tempImgSpin = QtGui.QSpinBox(self.horizontalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempImgSpin.sizePolicy().hasHeightForWidth())
        self.tempImgSpin.setSizePolicy(sizePolicy)
        self.tempImgSpin.setMaximumSize(QtCore.QSize(68, 16777215))
        self.tempImgSpin.setMinimum(1)
        self.tempImgSpin.setMaximum(200)
        self.tempImgSpin.setProperty("value", 48)
        self.tempImgSpin.setObjectName(_fromUtf8("tempImgSpin"))
        self.horizontalLayout_5.addWidget(self.tempImgSpin)
        self.tempImgBtn = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.tempImgBtn.setMinimumSize(QtCore.QSize(68, 0))
        self.tempImgBtn.setMaximumSize(QtCore.QSize(68, 16777215))
        self.tempImgBtn.setFlat(False)
        self.tempImgBtn.setObjectName(_fromUtf8("tempImgBtn"))
        self.horizontalLayout_5.addWidget(self.tempImgBtn)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.horizontalLayout_10.addWidget(self.configWidget)
        self.mainWidget.addWidget(self.configPage)
        self.verticalLayout_3.addWidget(self.mainWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.answerKey = QtGui.QAction(MainWindow)
        self.answerKey.setObjectName(_fromUtf8("answerKey"))
        self.levelKey5 = QtGui.QAction(MainWindow)
        self.levelKey5.setObjectName(_fromUtf8("levelKey5"))
        self.levelKey4 = QtGui.QAction(MainWindow)
        self.levelKey4.setObjectName(_fromUtf8("levelKey4"))
        self.levelKey3 = QtGui.QAction(MainWindow)
        self.levelKey3.setObjectName(_fromUtf8("levelKey3"))
        self.levelKey2 = QtGui.QAction(MainWindow)
        self.levelKey2.setObjectName(_fromUtf8("levelKey2"))
        self.levelKey1 = QtGui.QAction(MainWindow)
        self.levelKey1.setObjectName(_fromUtf8("levelKey1"))
        self.dismissAct = QtGui.QAction(MainWindow)
        self.dismissAct.setObjectName(_fromUtf8("dismissAct"))
        self.quickEvaluateKey5 = QtGui.QAction(MainWindow)
        self.quickEvaluateKey5.setObjectName(_fromUtf8("quickEvaluateKey5"))
        self.quickEvaluateKey4 = QtGui.QAction(MainWindow)
        self.quickEvaluateKey4.setObjectName(_fromUtf8("quickEvaluateKey4"))
        self.quickEvaluateKey3 = QtGui.QAction(MainWindow)
        self.quickEvaluateKey3.setObjectName(_fromUtf8("quickEvaluateKey3"))
        self.quickEvaluateKey2 = QtGui.QAction(MainWindow)
        self.quickEvaluateKey2.setObjectName(_fromUtf8("quickEvaluateKey2"))
        self.quickEvaluateKey1 = QtGui.QAction(MainWindow)
        self.quickEvaluateKey1.setObjectName(_fromUtf8("quickEvaluateKey1"))
        self.levelKey0 = QtGui.QAction(MainWindow)
        self.levelKey0.setObjectName(_fromUtf8("levelKey0"))
        self.quickEvaluateKey0 = QtGui.QAction(MainWindow)
        self.quickEvaluateKey0.setObjectName(_fromUtf8("quickEvaluateKey0"))
        self.resetAct = QtGui.QAction(MainWindow)
        self.resetAct.setObjectName(_fromUtf8("resetAct"))
        self.nextItemAct = QtGui.QAction(MainWindow)
        self.nextItemAct.setObjectName(_fromUtf8("nextItemAct"))
        self.nextPageAct = QtGui.QAction(MainWindow)
        self.nextPageAct.setObjectName(_fromUtf8("nextPageAct"))
        self.prevItemAct = QtGui.QAction(MainWindow)
        self.prevItemAct.setObjectName(_fromUtf8("prevItemAct"))
        self.prevPageAct = QtGui.QAction(MainWindow)
        self.prevPageAct.setObjectName(_fromUtf8("prevPageAct"))
        self.firstPageAct = QtGui.QAction(MainWindow)
        self.firstPageAct.setObjectName(_fromUtf8("firstPageAct"))
        self.lastPageAct = QtGui.QAction(MainWindow)
        self.lastPageAct.setObjectName(_fromUtf8("lastPageAct"))

        self.retranslateUi(MainWindow)
        self.mainWidget.setCurrentIndex(0)
        self.mainStk.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Making Things Done", None))
        self.titleLbl.setText(_translate("MainWindow", "MTD", None))
        self.searchLE.setPlaceholderText(_translate("MainWindow", "快速搜索…", None))
        self.userMenuBtn.setText(_translate("MainWindow", "USER", None))
        self.inboxBtn.setText(_translate("MainWindow", "  收件箱", None))
        self.starListBtn.setText(_translate("MainWindow", "  星标清单", None))
        self.todayBtn.setText(_translate("MainWindow", "  今天", None))
        self.weekBtn.setText(_translate("MainWindow", "  本周", None))
        self.addListBtn.setText(_translate("MainWindow", "  添加清单", None))
        self.manageListBtn.setText(_translate("MainWindow", "  管理清单", None))
        self.addTaskBtn.setText(_translate("MainWindow", "+", None))
        self.addTaskLE.setPlaceholderText(_translate("MainWindow", "添加任务…", None))
        self.taskLbl.setText(_translate("MainWindow", "TaskName", None))
        self.onManualBtn.setText(_translate("MainWindow", "手工记录", None))
        self.timerBtn.setText(_translate("MainWindow", "计时", None))
        self.addSubtaskBtn.setText(_translate("MainWindow", "+", None))
        self.addSubtaskLE.setPlaceholderText(_translate("MainWindow", "添加子任务…", None))
        self.timerTitleLbl.setText(_translate("MainWindow", "taskTitle", None))
        self.startBtn.setText(_translate("MainWindow", "开始", None))
        self.resetBtn.setText(_translate("MainWindow", "重置", None))
        self.stopBtn.setText(_translate("MainWindow", "终止", None))
        self.recordTitleLbl.setText(_translate("MainWindow", "recordTitle", None))
        self.label.setText(_translate("MainWindow", "日期", None))
        self.label_3.setText(_translate("MainWindow", "时间", None))
        self.label_7.setText(_translate("MainWindow", "分", None))
        self.label_8.setText(_translate("MainWindow", "学习量", None))
        self.slashLbl.setText(_translate("MainWindow", "-", None))
        self.rangeCB.setText(_translate("MainWindow", "按范围输入", None))
        self.saveBtn.setText(_translate("MainWindow", "记录", None))
        self.label_9.setText(_translate("MainWindow", "小时", None))
        self.unitLbl.setText(_translate("MainWindow", "页", None))
        self.addListTaskBtn.setText(_translate("MainWindow", "+", None))
        self.addListTaskLE.setPlaceholderText(_translate("MainWindow", "添加任务…", None))
        self.label_11.setText(_translate("MainWindow", "单位", None))
        self.unitBtn.setText(_translate("MainWindow", "更新", None))
        self.randomBtn.setText(_translate("MainWindow", "随机", None))
        self.importBtn.setText(_translate("MainWindow", "导入", None))
        self.label_5.setText(_translate("MainWindow", "数据库:", None))
        self.dbPathBtn.setText(_translate("MainWindow", "浏览", None))
        self.settingsTitleLbl.setText(_translate("MainWindow", "设置", None))
        self.label_17.setText(_translate("MainWindow", "图片库:", None))
        self.imageBankBtn.setText(_translate("MainWindow", "浏览", None))
        self.label_2.setText(_translate("MainWindow", "课程名称:", None))
        self.label_26.setText(_translate("MainWindow", "图片格式:", None))
        self.imgFormatCombo.setItemText(0, _translate("MainWindow", "PNG", None))
        self.imgFormatCombo.setItemText(1, _translate("MainWindow", "JPG", None))
        self.imgFormatCombo.setItemText(2, _translate("MainWindow", "BMP", None))
        self.imgFormatCombo.setItemText(3, _translate("MainWindow", "GIF", None))
        self.label_10.setText(_translate("MainWindow", "语音库:", None))
        self.audioBankBtn.setText(_translate("MainWindow", "浏览", None))
        self.saveSettingsBtn.setText(_translate("MainWindow", "保存", None))
        self.label_4.setText(_translate("MainWindow", "模板编号:", None))
        self.label_6.setText(_translate("MainWindow", "背景图:", None))
        self.tempImgBtn.setText(_translate("MainWindow", "预览", None))
        self.answerKey.setText(_translate("MainWindow", "查看答案", None))
        self.answerKey.setToolTip(_translate("MainWindow", "看一下答案", None))
        self.levelKey5.setText(_translate("MainWindow", "掌握", None))
        self.levelKey5.setToolTip(_translate("MainWindow", "能迅速给出正确的答案", None))
        self.levelKey4.setText(_translate("MainWindow", "正确", None))
        self.levelKey4.setToolTip(_translate("MainWindow", "不能迅速给出答案,但确信自己的答案是正确的.", None))
        self.levelKey3.setText(_translate("MainWindow", "蒙对", None))
        self.levelKey3.setToolTip(_translate("MainWindow", "虽然答对了,但无法确信自己的答案是否正确.", None))
        self.levelKey2.setText(_translate("MainWindow", "蒙错", None))
        self.levelKey2.setToolTip(_translate("MainWindow", "不确定答案是哪个,蒙一下,结果没蒙对", None))
        self.levelKey1.setText(_translate("MainWindow", "眼熟", None))
        self.levelKey1.setToolTip(_translate("MainWindow", "仅仅看上去眼熟而已", None))
        self.dismissAct.setText(_translate("MainWindow", "排除", None))
        self.dismissAct.setToolTip(_translate("MainWindow", "排除选中词条", None))
        self.dismissAct.setShortcut(_translate("MainWindow", "Ctrl+D", None))
        self.quickEvaluateKey5.setText(_translate("MainWindow", "掌握", None))
        self.quickEvaluateKey5.setToolTip(_translate("MainWindow", "能迅速给出正确的答案", None))
        self.quickEvaluateKey5.setShortcut(_translate("MainWindow", "5", None))
        self.quickEvaluateKey4.setText(_translate("MainWindow", "正确", None))
        self.quickEvaluateKey4.setToolTip(_translate("MainWindow", "不能迅速给出答案,但确信自己的答案是正确的.", None))
        self.quickEvaluateKey4.setShortcut(_translate("MainWindow", "4", None))
        self.quickEvaluateKey3.setText(_translate("MainWindow", "蒙对", None))
        self.quickEvaluateKey3.setToolTip(_translate("MainWindow", "虽然答对了,但无法确信自己的答案是否正确.", None))
        self.quickEvaluateKey3.setShortcut(_translate("MainWindow", "3", None))
        self.quickEvaluateKey2.setText(_translate("MainWindow", "蒙错", None))
        self.quickEvaluateKey2.setToolTip(_translate("MainWindow", "不确定答案是哪个,蒙一下,结果没蒙对", None))
        self.quickEvaluateKey2.setShortcut(_translate("MainWindow", "2", None))
        self.quickEvaluateKey1.setText(_translate("MainWindow", "眼熟", None))
        self.quickEvaluateKey1.setToolTip(_translate("MainWindow", "仅仅看上去眼熟而已", None))
        self.quickEvaluateKey1.setShortcut(_translate("MainWindow", "1", None))
        self.levelKey0.setText(_translate("MainWindow", "陌生", None))
        self.levelKey0.setToolTip(_translate("MainWindow", "看到这个词,我就象看到陌生人一样", None))
        self.quickEvaluateKey0.setText(_translate("MainWindow", "陌生", None))
        self.quickEvaluateKey0.setToolTip(_translate("MainWindow", "看到这个词,我就象看到陌生人一样", None))
        self.quickEvaluateKey0.setShortcut(_translate("MainWindow", "0", None))
        self.resetAct.setText(_translate("MainWindow", "重置", None))
        self.resetAct.setToolTip(_translate("MainWindow", "重置当前选中词条进度", None))
        self.resetAct.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.nextItemAct.setText(_translate("MainWindow", "下一条", None))
        self.nextItemAct.setToolTip(_translate("MainWindow", "移到下一条", None))
        self.nextItemAct.setShortcut(_translate("MainWindow", "S", None))
        self.nextPageAct.setText(_translate("MainWindow", "下一页", None))
        self.nextPageAct.setToolTip(_translate("MainWindow", "移到下一页", None))
        self.nextPageAct.setShortcut(_translate("MainWindow", "D", None))
        self.prevItemAct.setText(_translate("MainWindow", "上一条", None))
        self.prevItemAct.setToolTip(_translate("MainWindow", "移到上一条", None))
        self.prevItemAct.setShortcut(_translate("MainWindow", "W", None))
        self.prevPageAct.setText(_translate("MainWindow", "上一页", None))
        self.prevPageAct.setToolTip(_translate("MainWindow", "移到下一页", None))
        self.prevPageAct.setShortcut(_translate("MainWindow", "A", None))
        self.firstPageAct.setText(_translate("MainWindow", "首页", None))
        self.firstPageAct.setToolTip(_translate("MainWindow", "移到首页", None))
        self.firstPageAct.setShortcut(_translate("MainWindow", "Home", None))
        self.lastPageAct.setText(_translate("MainWindow", "末页", None))
        self.lastPageAct.setToolTip(_translate("MainWindow", "移到末页", None))
        self.lastPageAct.setShortcut(_translate("MainWindow", "End", None))

import image_rc
import stylesheets_rc
